jack_start: support both m2 & jam
Signed-off-by: Stanislav Fomichev <s@fomichev.me>

diff --git a/bin/jack_start b/bin/jack_start
--- a/bin/jack_start
+++ b/bin/jack_start
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-set -ex
+set -e
+set -x
 
 function cleanup {
 	set +e
@@ -15,21 +16,78 @@ function cleanup {
 }
 trap cleanup EXIT
 
-DEV_EXT=hw:Jam
-DEV_INT=hw:PCH
+CARDS=/proc/asound/cards
 
-#sudo alsactl store
-#sudo alsactl restore
+wait_for_card() {
+	while :; do
+		if grep -q "USB-Audio - Jam" $CARDS; then
+			echo "hw:Jam"
+			return
+		elif grep -q "USB-Audio - M2" $CARDS; then
+			echo "hw:M2"
+			return
+		fi
 
-# list devices
-cat /proc/asound/cards
+		echo "No card found, sleeping..." >&2
+		sleep 1
+	done
+}
 
-pasuspender -- jackd -d alsa -d "$DEV_EXT" -r 48000 -n 3 -p 64 -C &
+DEV_IN=$(wait_for_card)
+if [ -z "$DEV_IN" ]; then
+	echo "Sound card not found!"
+	exit 1
+fi
+
+case "$DEV_IN" in
+	hw:Jam)
+		# Apogee Jam does not have an output, use system.
+		DEV_OUT=hw:PCH
+		JACK_MODE="--capture"
+		JACK_RATE=32000
+		JACK_NPERIODS=4
+		JACK_PERIOD=128
+		;;
+	hw:M2)
+		DEV_OUT=hw:M2
+		JACK_MODE="--duplex"
+		JACK_RATE=48000
+		JACK_NPERIODS=3
+		JACK_PERIOD=128
+		;;
+	*)
+		echo "Unknown sound card!"
+		exit 1
+		;;
+esac
+
+echo "Using $DEV_IN -> $DEV_OUT"
+
+pasuspender -- jackd -d alsa -d "$DEV_IN" \
+	--rate $JACK_RATE \
+	--nperiods $JACK_NPERIODS \
+	--period $JACK_PERIOD \
+	$JACK_MODE &
+
+if [ "$DEV_OUT" = "hw:PCH" ]; then
+	sleep 1
+	alsa_out -d "$DEV_OUT" &
+fi
+
 sleep 1
-alsa_out -d "$DEV_INT" &
-sleep 1
-#guitarix -i system:capture_1 &
+
+guitarix -i system:capture_1 &
 qjackctl &
-#~/src/ardour/sysroot/bin/ardour6 &
+
+sleep 3
+jack_lsp -c
+
+# M2
+jack_connect "system:playback_1" "gx_head_fx:out_0" || :
+jack_connect "system:playback_2" "gx_head_fx:out_1" || :
+
+# Jam
+jack_connect "alsa_out:playback_1" "gx_head_fx:out_0" || :
+jack_connect "alsa_out:playback_2" "gx_head_fx:out_1" || :
 
 wait
